server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 172.19.168.25:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 172.19.168.25
    virtual-host: /wade
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:10086/eureka