server:
  port: 10086
spring:
  application:
    name: ly-registry
eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:10086/eureka
    register-with-eureka: true
    fetch-registry: true