server:
  port: 8084
spring:
  application:
    name: goods-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 172.19.168.25
    virtual-host: /wade
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:10086/eureka

