server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://0.0.0.0:10086/eureka
spring:
  application:
    name: api-gateway
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service:
      path: /search/**
      serviceId: search-service
      strip-prefix: false
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    user-service: /user/**
    cart-service: /cart/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
fly:
  jwt:
    cookieName: FLY_COOKIE
  filter:
    allow-paths:
      - /api/user/login
      - /api/item
      - /api/search